from pathlib import Path
from typing import Any, Dict, Iterable, Optional

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt

from app.artifacts import artifact_path


class DOCXArtifactGenerator:
    """
    Generates professional Word documents from structured
    local AI workflow results.

    The generator contains no network functionality.
    """

    def generate_approval_note(
        self,
        *,
        title: str,
        summary: str,
        findings: Iterable[str] | None = None,
        recommendations: Iterable[str] | None = None,
        knowledge_context: Iterable[Dict[str, Any]] | None = None,
        uncertainties: Iterable[str] | None = None,
        source_document: Optional[str] = None,
        filename: str = "inspection_approval_note.docx",
    ) -> Dict[str, Any]:
        """
        Generate an approval note and save it under data/artifacts/.
        """

        output_path = artifact_path(filename)

        document = Document()

        # ------------------------------------------------------
        # Base document formatting
        # ------------------------------------------------------

        styles = document.styles

        normal = styles["Normal"]
        normal.font.name = "Arial"
        normal.font.size = Pt(10)

        # ------------------------------------------------------
        # Title
        # ------------------------------------------------------

        heading = document.add_heading(
            title,
            level=0,
        )

        heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # ------------------------------------------------------
        # Metadata
        # ------------------------------------------------------

        metadata = document.add_paragraph()

        if source_document:
            metadata.add_run(
                "Source Document: "
            ).bold = True

            metadata.add_run(
                str(source_document)
            )

        metadata.add_run(
            "\nGenerated by: Sovereign AI Workbench"
        )

        metadata.add_run(
            "\nProcessing Mode: Local / Sovereign"
        )

        # ------------------------------------------------------
        # Executive Summary
        # ------------------------------------------------------

        document.add_heading(
            "1. Executive Summary",
            level=1,
        )

        document.add_paragraph(
            summary or "No summary was provided."
        )

        # ------------------------------------------------------
        # Findings
        # ------------------------------------------------------

        document.add_heading(
            "2. Inspection Findings",
            level=1,
        )

        self._add_bullets(
            document,
            findings,
            empty_message="No specific findings were provided.",
        )

        # ------------------------------------------------------
        # Recommendations
        # ------------------------------------------------------

        document.add_heading(
            "3. Recommended Action",
            level=1,
        )

        self._add_bullets(
            document,
            recommendations,
            empty_message=(
                "No specific recommendation was provided."
            ),
        )

        # ------------------------------------------------------
        # Organizational Knowledge
        # ------------------------------------------------------

        document.add_heading(
            "4. Relevant Organizational Knowledge",
            level=1,
        )

        knowledge_items = list(
            knowledge_context or []
        )

        if knowledge_items:
            for item in knowledge_items:
                paragraph = document.add_paragraph(
                    style="List Bullet"
                )

                source = item.get(
                    "source",
                    "Unknown source",
                )

                text = item.get(
                    "text",
                    "",
                )

                paragraph.add_run(
                    f"[{source}] "
                ).bold = True

                paragraph.add_run(
                    str(text)
                )
        else:
            document.add_paragraph(
                "No organizational knowledge was retrieved."
            )

        # ------------------------------------------------------
        # Uncertainties
        # ------------------------------------------------------

        document.add_heading(
            "5. Uncertainties / Items Requiring Review",
            level=1,
        )

        self._add_bullets(
            document,
            uncertainties,
            empty_message=(
                "No additional uncertainties were reported."
            ),
        )

        # ------------------------------------------------------
        # Approval
        # ------------------------------------------------------

        document.add_heading(
            "6. Approval",
            level=1,
        )

        approval_table = document.add_table(
            rows=3,
            cols=2,
        )

        approval_table.style = "Table Grid"

        approval_table.cell(0, 0).text = "Prepared By"
        approval_table.cell(0, 1).text = ""

        approval_table.cell(1, 0).text = "Reviewed By"
        approval_table.cell(1, 1).text = ""

        approval_table.cell(2, 0).text = "Approval / Decision"
        approval_table.cell(2, 1).text = ""

        # ------------------------------------------------------
        # Footer
        # ------------------------------------------------------

        section = document.sections[0]

        footer = section.footer.paragraphs[0]

        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

        footer.add_run(
            "Sovereign AI Workbench | Local processing | "
            "Human review required"
        )

        # ------------------------------------------------------
        # Save
        # ------------------------------------------------------

        document.save(output_path)

        return {
            "status": "created",
            "artifact_type": "docx",
            "filename": output_path.name,
            "path": str(output_path),
            "size_bytes": output_path.stat().st_size,
        }

    @staticmethod
    def _add_bullets(
        document: Document,
        items: Iterable[str] | None,
        *,
        empty_message: str,
    ) -> None:

        values = [
            str(item).strip()
            for item in (items or [])
            if str(item).strip()
        ]

        if not values:
            document.add_paragraph(
                empty_message
            )
            return

        for item in values:
            document.add_paragraph(
                item,
                style="List Bullet",
            )