import { useEffect, useState } from 'react'
import { artifactDownloadUrl, listTasks } from '../api/client'
import { Badge, EmptyState, ErrorBanner, Panel, Spinner } from '../components/ui'
import './ArtifactsPage.css'

interface ArtifactItem {
  taskId: string
  path: string
  filename: string
  ext: string
  type: string
  createdAt?: string
  validated: boolean
}

export default function ArtifactsPage() {
  const [artifacts, setArtifacts] = useState<ArtifactItem[] | null>(null)
  const [filter, setFilter] = useState<string>('all')
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    listTasks()
      .then((res) => {
        const extracted: ArtifactItem[] = []

        for (const task of res.tasks) {
          const path = task.metadata?.artifact_path as string | undefined
          if (!path) continue

          const filename = path.split(/[/\\]/).pop() || path
          const ext = filename.slice(filename.lastIndexOf('.')).toLowerCase()

          extracted.push({
            taskId: task.task_id,
            path,
            filename,
            ext,
            type: (task.metadata?.artifact_type as string) ?? (ext === '.docx' ? 'Approval Note' : ext === '.xlsx' ? 'Findings Sheet' : ext === '.py' ? 'Sandbox Script' : 'Document'),
            createdAt: task.created_at,
            validated: Boolean(task.metadata?.artifact_validation ?? true),
          })
        }

        setArtifacts(extracted.reverse())
      })
      .catch((err) => setError(err instanceof Error ? err.message : 'Failed to load artifacts history'))
  }, [])

  const filtered = artifacts?.filter((item) => {
    if (filter === 'all') return true
    if (filter === 'docx') return item.ext === '.docx'
    if (filter === 'xlsx') return item.ext === '.xlsx' || item.ext === '.csv'
    if (filter === 'code') return item.ext === '.py'
    return true
  })

  function getFormatTag(ext: string) {
    if (ext === '.docx' || ext === '.doc') return 'DOCX'
    if (ext === '.xlsx' || ext === '.xls' || ext === '.csv') return 'XLSX'
    if (ext === '.py') return 'PY'
    if (ext === '.pdf') return 'PDF'
    return 'FILE'
  }

  return (
    <div className="artifacts-page">
      <div className="artifacts-header">
        <div>
          <h1>Deliverables &amp; Generated Artifacts</h1>
          <p className="artifacts-desc">
            All official documents, approval notes, spreadsheets, and verified scripts generated by the sovereign agent are persisted locally on-premises in <code>data/artifacts/</code>.
          </p>
        </div>

        {/* Filter Chips */}
        <div className="filter-chips">
          <button
            className={`filter-chip ${filter === 'all' ? 'active' : ''}`}
            onClick={() => setFilter('all')}
          >
            All Files ({artifacts ? artifacts.length : 0})
          </button>
          <button
            className={`filter-chip ${filter === 'docx' ? 'active' : ''}`}
            onClick={() => setFilter('docx')}
          >
            Word (.docx)
          </button>
          <button
            className={`filter-chip ${filter === 'xlsx' ? 'active' : ''}`}
            onClick={() => setFilter('xlsx')}
          >
            Excel (.xlsx)
          </button>
          <button
            className={`filter-chip ${filter === 'code' ? 'active' : ''}`}
            onClick={() => setFilter('code')}
          >
            Python (.py)
          </button>
        </div>
      </div>

      {error && <ErrorBanner title="Artifacts Storage Notice" message={error} />}

      <Panel title="On-Premise Generated Deliverables">
        {!artifacts && !error && (
          <div className="artifacts-loading">
            <Spinner size="md" /> Loading generated files catalog…
          </div>
        )}

        {artifacts && artifacts.length === 0 && (
          <EmptyState
            message="No deliverable documents or scripts have been generated yet. Run an agent task to produce Word approval notes, spreadsheets, or code."
          />
        )}

        {filtered && filtered.length > 0 && (
          <div className="artifacts-cards-grid">
            {filtered.map((item, i) => (
              <div key={i} className="artifact-item-card">
                <div className="artifact-item-header">
                  <span className="artifact-item-tag">{getFormatTag(item.ext)}</span>
                  <div className="artifact-item-meta">
                    <span className="artifact-item-name">{item.filename}</span>
                    <span className="artifact-item-sub">{item.type}</span>
                  </div>
                  {item.validated && (
                    <Badge tone="ok" size="sm">✓ Validated</Badge>
                  )}
                </div>

                <div className="artifact-item-details">
                  <div className="detail-row">
                    <span className="detail-label">Task ID:</span>
                    <code className="detail-task">{item.taskId.slice(0, 8)}</code>
                  </div>
                  <div className="detail-row">
                    <span className="detail-label">Storage Path:</span>
                    <span className="detail-path">{item.path}</span>
                  </div>
                </div>

                <div className="artifact-item-action">
                  <a
                    className="artifact-download-btn"
                    href={artifactDownloadUrl(item.path)}
                    download
                  >
                    Download Official File
                  </a>
                </div>
              </div>
            ))}
          </div>
        )}
      </Panel>
    </div>
  )
}
